{
 "title": "Kueue overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" }
  ]
 },
 "panels": [
  {
   "title": "Admissions /s",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kueue_admission_attempts_total[60s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Admission latency [99th perc]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(histogram_quantile(0.99, rate(kueue_admission_attempt_duration_seconds_bucket[60s]))>0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active workloads",
   "type": "stat",
   "description": "The total number of all active workloads in all cluster queues",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kueue_admitted_active_workloads)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending workloads",
   "type": "stat",
   "description": "The total number of all pending workloads in all cluster queues",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kueue_pending_workloads)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total nodes",
   "type": "stat",
   "description": "The total number of nodes in a cluster",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kube_node_info)", "legendFormat": "__auto" }
   ]
  },
  { "title": "Cluster queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Active workloads per cluster queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by(cluster_queue)(kueue_admitted_active_workloads)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending workloads per cluster queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 5 },
   "targets": [
    {
     "expr": "sum by(cluster_queue)(kueue_pending_workloads)",
     "internal": "${resolution}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cluster nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "CPU requested",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"}) / sum(kube_node_status_allocatable{resource=\"cpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory requested",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"}) / sum(kube_node_status_allocatable{resource=\"memory\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ready nodes",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"true\"}) / sum(kube_node_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes ready",
   "type": "stat",
   "description": "The total number of nodes with Ready == true condition",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes not ready",
   "type": "stat",
   "description": "The total number of nodes with Ready == false condition",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"false\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes unschedulable",
   "type": "stat",
   "description": "The total number of nodes that can't schedule PODs",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_spec_unschedulable)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes disk pressure",
   "type": "stat",
   "description": "The total number of nodes with DiskPressure condition",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"DiskPressure\",status=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes mem pressure",
   "type": "stat",
   "description": "The total number of nodes with MemPressure condition",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"MemoryPressure\",status=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes PID pressure",
   "type": "stat",
   "description": "The total number of nodes with PIDPressure condition",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"PIDPressure\",status=\"true\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"true\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_node_status_condition{condition=\"Ready\",status=\"false\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}