apiVersion: batch/v1
kind: Job
metadata:
  generateName: video-downloader-job-
  namespace: video
  annotations:
    kueue.x-k8s.io/queue-name: video-downloader-queue
spec:
  parallelism: 1
  completions: 1
  suspend: true
  template:
    spec:
      serviceAccountName: video-downloader-service-account
      automountServiceAccountToken: true        
      containers:
      - name: video-downloader
        image: europe-west1-docker.pkg.dev/g-prj-cd-sb-ae-01/registry/video-downloader:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 250m
            memory: 250Mi
        env:
        - name: BUCKET
          value: $bucket
        - name: COLLECTION
          value: $collection
        - name: ITEM
          value: $item
        - name: FILE
          value: $file
      restartPolicy: Never      